from django import forms

class UpdateAccountForm(forms.Form):
    status = forms.DecimalField(max_value=1,min_value=0,max_digits=1)
    service = forms.DecimalField(min_value=-1,decimal_places=0)
    newservice = forms.CharField(max_length=100,required=False)
    accountid = forms.CharField(max_length=100)
    updatepwd = forms.DecimalField(max_value=1,min_value=0,max_digits=1)
    password = forms.CharField(max_length=100,required=False)
    password_conf = forms.CharField(max_length=100,required=False)
    mailaddr1 = forms.DecimalField(min_value=-2,decimal_places=0)
    newmail1 = forms.EmailField(required=False)
    mailaddr2 = forms.DecimalField(min_value=-2,decimal_places=0)
    newmail2 = forms.EmailField(required=False)
    mailaddr3 = forms.DecimalField(min_value=-2,decimal_places=0)
    newmail3 = forms.EmailField(required=False)
    address = forms.DecimalField(min_value=-2,decimal_places=0)
    newaddress = forms.CharField(max_length=200,required=False)
    phonenum = forms.DecimalField(min_value=-2,decimal_places=0)
    newphonenum = forms.CharField(max_length=20,required=False)
    link1 = forms.DecimalField(min_value=-2,decimal_places=0)
    link2 = forms.DecimalField(min_value=-2,decimal_places=0)
    link3 = forms.DecimalField(min_value=-2,decimal_places=0)
    multifactor_type = forms.CharField(max_length=100,required=False)
    multifactor_info = forms.CharField(max_length=100,required=False)
    secq1 = forms.CharField(max_length=200,required=False)
    seca1 = forms.CharField(max_length=200,required=False)
    secq2 = forms.CharField(max_length=200,required=False)
    seca2 = forms.CharField(max_length=200,required=False)
    secq3 = forms.CharField(max_length=200,required=False)
    seca3 = forms.CharField(max_length=200,required=False)
    register_date = forms.DateField(required=False)
    unregister_date = forms.DateField(required=False)
    memo = forms.CharField(required=False)

